version: '3.8'
name: 'scrutiny-cspm'

services:
  app:
    build: .
    container_name: scrutiny-cspm
    ports:
      - "3000:3000"
    volumes:
      - ./scans:/scans
      - ~/.aws:/root/.aws
    env_file:
      - .env
  opa:
    container_name: opa
    image: openpolicyagent/opa:latest-debug
    ports:
      - "8181:8181"