- hosts: localhost
  gather_facts: false
  vars:
    aws_region: us-east-1
  tasks:
    - name: Retrieve AWS S3 buckets
      aws_s3_bucket_info:
        region: "{{ aws_region }}"
      register: s3_buckets

    - name: Set the variable in the fact cache
      set_fact:
        s3_buckets_info: "{{ s3_buckets.buckets }}"
        cacheable: yes

    - name: Print S3 bucket names and specified attributes
      debug:
        msg: |
          Bucket Name: {{ item.name }}
          Creation Date: {{ item.creation_date }}
          Encryption: {{ item.encryption.rules | default('None') }}
          Public Access Block: {{ item.public_access_block | default('None') }}
          Versioning: {{ item.versioning.status | default('Disabled') }}
      loop: "{{ s3_buckets_info }}"