cli:
  test: value

logging:
  level: DEBUG

commands:
  certificate: 
    module: commands.certificate_command
    class_name: CertificateCommand

  test:
    module: commands.test_command
    class_name: TestCommand
  aws:
    module: commands.aws_root_command
    class_name: AWSRootCommand
  azure:
    module: commands.azure_root_command
    class_name: AzureRootCommand
  

policy:
  github:
    repository: robertfischer3/snarfswap
    namespace: scrutiny-cspm-policy-test
    policy_repo: robertfischer3/snarfswap
    branch: main
    path: policy
