cli:
  test: value

logging:
  level: DEBUG

commands:
  certificate: 
    module: commands.certificate_command
    class_name: CertificateCommand
  inventory: 
    module: commands.inventory_command
    class_name: InventoryCommand
  test:
    module: commands.test_command
    class_name: TestCommand
  opa_create:
    module: commands.opa_create_command
    class_name: OpaCreateCommand

policies:
  namespace: 
    - scrutiny-cspm
  policy_repo: 
      - https://github.com/ericmarg/ScrutinyCSPM
  branch: main
  path: policies
